# Generated by Django 3.1 on 2020-08-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPM', '0002_auto_20200831_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateField(),
        ),
    ]
