# Generated by Django 3.1 on 2020-08-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VPM', '0003_auto_20200831_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
